/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a6f08f5e-0025-4a79-9446-9a84bdcc557e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tMs2gfGRJ",
    "aws_user_pools_web_client_id": "1ffs1um4m61js1q19mf7ditc6g",
    "oauth": {},
    "aws_user_files_s3_bucket": "pageforseowon157a9bedba8647de9bb3b81b5b2f349b235658-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
